// Generated by CoffeeScript 1.6.2
(function() {
  var config, gridSpacing, nodeSize;

  config = {
    showLines: false,
    filterRadicals: function(radicals) {
      return radicals.slice(0, 14);
    },
    filterLinkedRadicals: function(radicals) {
      return radicals;
    },
    sunflowerKanjis: true,
    kmeansInitialVectorsRandom: false,
    kmeansClustersN: -1,
    forceGraph: false,
    circularLines: false,
    nodeSize: nodeSize = 12,
    gridSpacing: gridSpacing = nodeSize * 8,
    debugOverlay: false,
    transitionTime: 2000,
    initialScale: 1,
    edgesBeforeSnap: false,
    timeToOptimize: 3000,
    optimizeMaxLoops: 0,
    optimizeMaxSteps: 0,
    slideshowSteps: 1,
    showInitialMode: true,
    debugKanji: '類',
    overlengthEdge: gridSpacing * 3,
    kanjiOffset: 4,
    optimizer: true
  };

  if (typeof window !== "undefined" && window !== null) {
    window.config = config;
  }

  if (typeof self !== "undefined" && self !== null) {
    self.config = config;
  }

}).call(this);

/*
//@ sourceMappingURL=config.map
*/
