// Generated by CoffeeScript 1.6.2
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  define(['utils'], function(utils) {
    var Edge, Graph, Line, Node, P;

    P = utils.P;
    Node = (function() {
      var next_id;

      next_id = 0;

      function Node(_arg) {
        var _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7;

        _ref = _arg != null ? _arg : {}, this.x = _ref.x, this.y = _ref.y, this.lines = _ref.lines, this.edges = _ref.edges, this.data = _ref.data, this.style = _ref.style, this.id = _ref.id;
        if ((_ref1 = this.x) == null) {
          this.x = 0;
        }
        if ((_ref2 = this.y) == null) {
          this.y = 0;
        }
        if ((_ref3 = this.lines) == null) {
          this.lines = [];
        }
        if ((_ref4 = this.edges) == null) {
          this.edges = [];
        }
        if ((_ref5 = this.data) == null) {
          this.data = {};
        }
        if ((_ref6 = this.style) == null) {
          this.style = {};
        }
        if ((_ref7 = this.id) == null) {
          this.id = next_id++;
        }
      }

      Node.prototype.coord = function() {
        return this.x + "x" + this.y;
      };

      return Node;

    })();
    Edge = (function() {
      function Edge(_arg) {
        var _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7;

        _ref = _arg != null ? _arg : {}, this.source = _ref.source, this.target = _ref.target, this.line = _ref.line, this.radical = _ref.radical;
        if (this.radical) {
          throw this.radical;
        }
        if ((_ref1 = this.source) == null) {
          this.source = null;
        }
        if ((_ref2 = this.target) == null) {
          this.target = null;
        }
        if ((_ref3 = this.sourcetrans) == null) {
          this.sourcetrans = null;
        }
        if ((_ref4 = this.targettrans) == null) {
          this.targettrans = null;
        }
        if ((_ref5 = this.line) == null) {
          this.line = null;
        }
        if ((_ref6 = this.style) == null) {
          this.style = {};
        }
        if ((_ref7 = this.calc) == null) {
          this.calc = false;
        }
      }

      Edge.prototype.getVector = function() {
        return [this.target.x - this.source.x, this.target.y - this.source.y];
      };

      Edge.prototype.getAngle = function(edge) {
        var angle, l1, l2, scalar, x1, x2, y1, y2, _ref, _ref1;

        _ref = this.getVector(), x1 = _ref[0], y1 = _ref[1];
        _ref1 = edge.getVector(), x2 = _ref1[0], y2 = _ref1[1];
        scalar = x1 * x2 + y1 * y2;
        l1 = Math.sqrt(Math.pow(x1, 2) + Math.pow(y1, 2));
        l2 = Math.sqrt(Math.pow(x2, 2) + Math.pow(y2, 2));
        return angle = Math.acos(scalar / (l1 * l2));
      };

      Edge.prototype.getEdgeAngle = function() {
        var angle, x, x1, x2, y, y1, y2, _ref, _ref1;

        _ref = [this.source.x, this.source.y], x1 = _ref[0], y1 = _ref[1];
        _ref1 = [this.target.x, this.target.y], x2 = _ref1[0], y2 = _ref1[1];
        x = x2 - x1;
        y = y2 - y1;
        return angle = Math.atan2(y, x);
      };

      Edge.prototype.lengthSqr = function() {
        var x, y, _ref;

        _ref = this.getVector(), x = _ref[0], y = _ref[1];
        return (Math.pow(x, 2)) + (Math.pow(y, 2));
      };

      return Edge;

    })();
    Line = (function() {
      var next_id;

      next_id = 0;

      function Line(_arg) {
        var _ref, _ref1, _ref2, _ref3, _ref4;

        _ref = _arg != null ? _arg : {}, this.nodes = _ref.nodes, this.edges = _ref.edges, this.data = _ref.data, this.id = _ref.id;
        if ((_ref1 = this.nodes) == null) {
          this.nodes = [];
        }
        if ((_ref2 = this.edges) == null) {
          this.edges = [];
        }
        if ((_ref3 = this.data) == null) {
          this.data = {};
        }
        if ((_ref4 = this.id) == null) {
          this.id = next_id++;
        }
      }

      return Line;

    })();
    Graph = (function() {
      function Graph(lines) {
        var edge, k, line, line_nodes, node, nodes, orig_line_nodes, source, target, _i, _j, _k, _l, _len, _len1, _len2, _len3, _ref, _ref1;

        this.nodes = [];
        this.edges = [];
        this.lines = [];
        nodes = [];
        for (_i = 0, _len = lines.length; _i < _len; _i++) {
          line_nodes = lines[_i];
          for (_j = 0, _len1 = line_nodes.length; _j < _len1; _j++) {
            node = line_nodes[_j];
            if (__indexOf.call(nodes, node) < 0) {
              nodes.push(node);
            }
          }
        }
        this.nodes = (function() {
          var _k, _len2, _results;

          _results = [];
          for (_k = 0, _len2 = nodes.length; _k < _len2; _k++) {
            node = nodes[_k];
            k = 0;
            if (node instanceof Node) {
              _results.push(node);
            } else {
              _results.push(new Node(node));
            }
          }
          return _results;
        })();
        this.lines = (function() {
          var _k, _len2, _results;

          _results = [];
          for (_k = 0, _len2 = lines.length; _k < _len2; _k++) {
            orig_line_nodes = lines[_k];
            line = new Line(orig_line_nodes.obj);
            line.nodes = (function() {
              var _l, _len3, _results1;

              _results1 = [];
              for (_l = 0, _len3 = orig_line_nodes.length; _l < _len3; _l++) {
                node = orig_line_nodes[_l];
                node = this.nodes[nodes.indexOf(node)];
                node.lines.push(line);
                _results1.push(node);
              }
              return _results1;
            }).call(this);
            _results.push(line);
          }
          return _results;
        }).call(this);
        _ref = this.lines;
        for (_k = 0, _len2 = _ref.length; _k < _len2; _k++) {
          line = _ref[_k];
          source = line.nodes[0];
          _ref1 = line.nodes.slice(1);
          for (_l = 0, _len3 = _ref1.length; _l < _len3; _l++) {
            target = _ref1[_l];
            edge = new Edge({
              source: source,
              target: target,
              line: line
            });
            source.edges.push(edge);
            target.edges.push(edge);
            this.edges.push(edge);
            line.edges.push(edge);
            source = target;
          }
        }
      }

      Graph.prototype.kanjis = function() {
        var node, _i, _len, _ref, _results;

        _ref = this.nodes;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          node = _ref[_i];
          if (node.data.kanji) {
            _results.push(node.data);
          }
        }
        return _results;
      };

      return Graph;

    })();
    return my.graph = {
      Node: Node,
      Edge: Edge,
      Line: Line,
      Graph: Graph
    };
  });

}).call(this);

/*
//@ sourceMappingURL=graph.map
*/
