// Generated by CoffeeScript 1.6.2
(function() {
  define(['utils'], function(_arg) {
    var History, P, arrayUnique;

    P = _arg.P, arrayUnique = _arg.arrayUnique;
    History = (function() {
      function History() {
        this.history = [];
        this.fclass = 'firsthisKanji';
        this.nclass = 'hisKanji';
        this.target = {};
      }

      History.prototype.addCentral = function(central) {
        this.history.unshift(central);
        return this.history = arrayUnique(this.history);
      };

      History.prototype.render = function() {
        var kanji, list, max_size, size, _i, _len, _ref;

        list = '<ul class=historylist>';
        max_size = 10;
        size = 0;
        _ref = this.history;
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          kanji = _ref[_i];
          if (size === max_size) {
            break;
          }
          if (size === 0) {

          } else {
            list = "" + list + " <li class=" + this.nclass + "> " + kanji + " </li>";
          }
          size = size + +'1';
        }
        list = "" + list + " </ul>";
        return list;
      };

      History.prototype.setup = function(eventtarget) {
        return this.target = eventtarget;
      };

      History.prototype.getCurrentCentral = function() {
        return this.history[0];
      };

      return History;

    })();
    return {
      History: History
    };
  });

}).call(this);

/*
//@ sourceMappingURL=history.map
*/
