// Generated by CoffeeScript 1.8.0
(function() {
  window.my = {
    kanjis: {},
    radicals: {},
    jouyou_radicals: {},
    jouyou: [],
    jouyou_grade: {},
    config: config
  };

  define('main', ['utils', 'load_data', 'interactivity', 'routing', 'prepare_data'], function(_arg, loadData, _arg1, _arg2, prepare) {
    var MetroMapLayout, P, View, async, copyAttrs, main, prettyDebug, showDebugOverlay, somePrettyPrint, styleZoom;
    P = _arg.P, somePrettyPrint = _arg.somePrettyPrint, styleZoom = _arg.styleZoom, async = _arg.async, prettyDebug = _arg.prettyDebug, copyAttrs = _arg.copyAttrs;
    View = _arg1.View;
    MetroMapLayout = _arg2.MetroMapLayout;
    main = function() {
      var body, kanjis, radicals, svg, view;
      body = my.body = d3.select('body');
      if (config.debugOverlay) {
        showDebugOverlay(body);
      }
      svg = my.svg = body.select('svg#graph');
      svg.g = svg.append('g');
      prepare.setupRadicalJouyous();
      prepare.setupKanjiGrades();
      prepare.setupKanjiRadicals(d3.values(my.kanjis), my.radicals);
      radicals = prepare.getRadicals();
      kanjis = prepare.getKanjis(radicals);
      view = my.view = new View({
        svg: svg,
        config: config,
        kanjis: kanjis,
        radicals: radicals
      });
      if (config.showInitialMode) {
        return view.doInitial();
      } else {
        return view.doSlideshow();
      }
    };
    showDebugOverlay = function(el) {
      return el.append('pre').attr({
        id: 'my'
      }).text(somePrettyPrint(my));
    };
    console.info('end of tests');
    return loadData(main);
  });

}).call(this);

//# sourceMappingURL=main.js.map
