// Generated by CoffeeScript 1.6.2
(function() {
  define(['graph'], function(_arg) {
    var Graph, createGraph, createNode;

    Graph = _arg.Graph;
    createNode = function() {
      return {
        x: Math.random(),
        y: Math.random()
      };
    };
    createGraph = function(lines, nodesPerLine) {
      var graph, line, node;

      lines = (function() {
        var _i, _results;

        _results = [];
        for (line = _i = 1; 1 <= lines ? _i <= lines : _i >= lines; line = 1 <= lines ? ++_i : --_i) {
          _results.push((function() {
            var _j, _results1;

            _results1 = [];
            for (node = _j = 1; 1 <= nodesPerLine ? _j <= nodesPerLine : _j >= nodesPerLine; node = 1 <= nodesPerLine ? ++_j : --_j) {
              _results1.push(createNode());
            }
            return _results1;
          })());
        }
        return _results;
      })();
      return graph = new Graph(lines);
    };
    return {
      graph100: createGraph(10, 18),
      graph10: createGraph(3, 18)
    };
  });

}).call(this);

/*
//@ sourceMappingURL=test_graph.map
*/
